package com.ttdt.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ttdt.modle.PlayList;
import com.ttdt.modle.User;

import com.ttdt.greendao.PlayListDao;
import com.ttdt.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playListDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PlayListDao playListDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playListDaoConfig = daoConfigMap.get(PlayListDao.class).clone();
        playListDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        playListDao = new PlayListDao(playListDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PlayList.class, playListDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        playListDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public PlayListDao getPlayListDao() {
        return playListDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
